language: python

env:
  global:
    ZOPE_INTERFACE_STRICT_IRO: 1

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3

jobs:
  include:
    - name: "Python: 2.7, minimal set of dependencies"
      python: 2.7
      env: MINIMAL=1

install:
  - pip install -U pip setuptools
  - pip install -U coveralls coverage
  - if [[ -n "$MINIMAL" ]]; then pip install -U -e ".[mintests]"; fi
  - if [[ -z "$MINIMAL" ]]; then pip install -U -e ".[test,docs]"; fi

script:
# Temporary workaround. Pending
# https://github.com/zopefoundation/zope.security/issues/71
# avoid zope.testrunner.
  - coverage run -m unittest discover -s src
  - if [[ -z "$MINIMAL" ]]; then sphinx-build              -b html    -d docs/_build/doctrees docs docs/_build/html; fi
  - if [[ -z "$MINIMAL" ]]; then coverage run -a -m sphinx -b doctest -d docs/_build/doctrees docs docs/_build/doctest; fi

after_success:
  - coveralls

notifications:
  email: false

cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
